name: Lint Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Modules
        run: npm ci

      - name: Run linting check
        run: npm run lint
